
# Data configuration
data:
  train_path: "data/processed_full/train_generation.pkl"
  val_path: "data/processed_full/test_generation.pkl"
  test_path: "data/processed_full/test_generation.pkl"
  batch_size: 16
  num_workers: 4
  pin_memory: true
  shuffle: true
  include_pocket: true
  augment: true
  max_atoms: 50

# Model architecture
model:
  atom_types: 11
  bond_types: 4
  hidden_dim: 256
  pocket_dim: 256
  num_layers: 4
  max_radius: 10.0
  max_pocket_atoms: 1000
  conditioning_type: "add"
  pocket_selection_strategy: "adaptive"
  interaction_radius: 8.0
  surface_probe_radius: 1.4

# DDPM diffusion parameters
ddpm:
  num_timesteps: 1000
  beta_schedule: "cosine"
  beta_start: 0.0001
  beta_end: 0.02
  loss_type: "mse"
  sampling_method: "ddpm"
  clip_denoised: true
  
# Training configuration
training:
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.0001
  grad_clip_norm: 1.0
  gradient_accumulation_steps: 1
  use_amp: true
  amp_dtype: "float16"
  
  scheduler:
    type: "cosine_annealing"
    T_max: 100
    eta_min: 0.00001
    warmup_epochs: 5
    warmup_lr: 0.00001

# Optimizer configuration (FIXED TYPES)
optimizer:
  type: "adamw"
  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001
  eps: 0.00000001  # Fixed: was string, now float

# Loss weights
loss_weights:
  noise_loss: 1.0
  atom_type_loss: 0.1
  bond_type_loss: 0.1
  geometry_loss: 0.05

# Logging configuration
logging:
  project_name: "crossdock-ddpm-molecular-generation"
  experiment_name: "ddpm-pocket-conditioning"
  log_every_n_steps: 50
  val_check_interval: 1000
  save_top_k: 3
  save_path: "models/ddpm/"
  use_wandb: false  # Disabled for test
  wandb_tags: ["ddpm", "molecular-generation", "crossdock"]
  visualize_molecules: true
  viz_frequency: 10
  num_viz_samples: 8

# Early stopping
early_stopping:
  monitor: "val_total_loss"
  patience: 15
  min_delta: 0.001
  mode: "min"

# Model checkpointing
checkpointing:
  monitor: "val_total_loss"
  save_best_only: true
  save_last: true
  mode: "min"
  filename: "ddpm-epoch-{epoch:02d}-loss-{val_total_loss:.4f}"

# Generation/Sampling configuration
generation:
  num_molecules: 100
  max_atoms: 50
  guidance_scale: 1.0
  num_sampling_steps: 1000
  eta: 0.0
  use_pocket_conditioning: true
  pocket_guidance_weight: 1.0

# Memory optimization
memory_optimization:
  gradient_checkpointing: false
  max_batch_size_auto_tune: false
  empty_cache_every_n_steps: 100
  max_pocket_atoms_per_batch: 500
  smart_pocket_selection: true

# Hardware configuration
hardware:
  device: "auto"
  precision: "mixed"
  deterministic: false
  benchmark: true

# Reproducibility
seed: 42
deterministic: false

# Advanced DDPM options
advanced_ddpm:
  rescale_betas_zero_snr: false
  clip_sample: true
  clip_sample_range: 1.0
  prediction_type: "epsilon"
  timestep_spacing: "leading"
  use_karras_sigmas: false
  sigma_min: 0.002
  sigma_max: 80.0

# Validation configuration
validation:
  val_frequency: 1
  num_val_samples: 100
  compute_metrics: true
  metrics:
    - "validity"
    - "uniqueness" 
    - "drug_likeness"

# Dataset-specific settings
dataset_config:
  crossdock_version: "pocket10"
  use_split_by_name: true
  center_molecules: true
  normalize_positions: false
  add_hydrogens: false
  rotation_augmentation: true
  noise_augmentation: true
  noise_scale: 0.1

# Debugging and development
debug:
  enable_debug_mode: false
  debug_batches: 10
  profile_training: false
  check_gradients: false
  visualize_first_batch: true
  print_model_summary: true
  log_memory_usage: false