# config/optimized_ddpm_config.yaml - Tối ưu cho training hiện tại
# Data configuration - Sử dụng data đã preprocessing
data:
  train_path: "data/processed_full/train_generation.pkl"
  val_path: "data/processed_full/test_generation.pkl"
  test_path: "data/processed_full/test_generation.pkl"
  batch_size: 8  # Giảm xuống để tránh OOM
  num_workers: 2  # Giảm để ổn định
  pin_memory: true
  shuffle: true
  include_pocket: true
  augment: true
  max_atoms: 50

# Model architecture - EGNN backend (proven & stable)
model:
  atom_types: 11
  bond_types: 4
  hidden_dim: 256
  pocket_dim: 256
  num_layers: 4  # Bắt đầu với 4 layers cho ổn định
  max_radius: 10.0
  max_pocket_atoms: 500  # Giảm để tiết kiệm memory
  conditioning_type: "add"
  pocket_selection_strategy: "adaptive"
  interaction_radius: 8.0
  surface_probe_radius: 1.4
  use_improved_pocket_encoder: true
  pocket_encoder_type: "improved"

# DDPM diffusion parameters - Proven settings
ddpm:
  num_timesteps: 1000
  beta_schedule: "cosine"
  beta_start: 0.0001
  beta_end: 0.02
  loss_type: "mse"
  sampling_method: "ddpm"
  clip_denoised: true
  rescale_betas_zero_snr: false
  clip_sample: true
  clip_sample_range: 1.0
  prediction_type: "epsilon"
  timestep_spacing: "leading"

# Training configuration - Conservative & stable
training:
  num_epochs: 50  # Bắt đầu với 50 epochs
  learning_rate: 0.0001
  weight_decay: 0.0001
  grad_clip_norm: 1.0
  gradient_accumulation_steps: 1
  use_amp: true  # Sử dụng mixed precision để tiết kiệm memory
  amp_dtype: "float16"
  warmup_epochs: 5
  
  scheduler:
    type: "cosine_annealing"
    T_max: 50
    eta_min: 0.00001
    warmup_epochs: 5
    warmup_lr: 0.00001

# Optimizer configuration - AdamW proven for molecular generation
optimizer:
  type: "adamw"
  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001
  eps: 0.00000001

# Loss weights - Balanced for DDPM
loss_weights:
  noise_loss: 1.0
  atom_type_loss: 0.1
  bond_type_loss: 0.1
  geometry_loss: 0.05
  position_loss: 1.0
  pocket_conditioning_loss: 0.02

# Logging configuration
logging:
  project_name: "molecular-ddpm-training"
  experiment_name: "egnn-ddpm-v1"
  log_every_n_steps: 50
  val_check_interval: 500  # Validate mỗi 500 steps
  save_top_k: 3
  save_path: "models/ddpm_trained/"
  use_wandb: false  # Tắt wandb để đơn giản
  wandb_tags: ["ddpm", "egnn", "molecular-generation"]
  visualize_molecules: true
  viz_frequency: 10
  num_viz_samples: 4

# Early stopping - Ngăn overfitting
early_stopping:
  monitor: "val_total_loss"
  patience: 10  # Stop nếu không improve trong 10 epochs
  min_delta: 0.001
  mode: "min"

# Model checkpointing
checkpointing:
  monitor: "val_total_loss"
  save_best_only: true
  save_last: true
  mode: "min"
  filename: "ddpm-epoch-{epoch:02d}-loss-{val_total_loss:.4f}"

# Generation/Sampling configuration
generation:
  num_molecules: 50
  max_atoms: 50
  guidance_scale: 1.0
  num_sampling_steps: 1000
  eta: 0.0
  use_pocket_conditioning: true
  pocket_guidance_weight: 1.0
  use_smart_pocket_selection: true
  generation_pocket_strategy: "adaptive"

# Memory optimization - Quan trọng để tránh OOM
memory_optimization:
  gradient_checkpointing: false
  max_batch_size_auto_tune: false
  empty_cache_every_n_steps: 100
  max_pocket_atoms_per_batch: 200  # Giảm để tiết kiệm memory
  smart_pocket_selection: true
  pocket_batch_size_limit: 100
  enable_atom_selection_caching: true

# Hardware configuration
hardware:
  device: "auto"  # Tự động detect GPU/CPU
  precision: "mixed"  # Mixed precision để tiết kiệm memory
  deterministic: false
  benchmark: true

# Reproducibility
seed: 42
deterministic: false

# Advanced DDPM options
advanced_ddpm:
  rescale_betas_zero_snr: false
  clip_sample: true
  clip_sample_range: 1.0
  prediction_type: "epsilon"
  timestep_spacing: "leading"
  use_karras_sigmas: false
  sigma_min: 0.002
  sigma_max: 80.0

# Validation configuration
validation:
  val_frequency: 1
  num_val_samples: 50
  compute_metrics: true
  metrics:
    - "validity"
    - "uniqueness" 
    - "drug_likeness"
    - "pocket_binding_affinity"

# Dataset-specific settings
dataset_config:
  crossdock_version: "pocket10"
  use_split_by_name: true
  center_molecules: true
  normalize_positions: false
  add_hydrogens: false
  rotation_augmentation: true
  noise_augmentation: true
  noise_scale: 0.1
  pocket_augmentation: true
  ligand_pocket_alignment: true

# Debugging and monitoring
debug:
  enable_debug_mode: false
  debug_batches: 5
  profile_training: false
  check_gradients: false
  visualize_first_batch: true
  print_model_summary: true
  log_memory_usage: true
  debug_pocket_selection: false
  log_pocket_selection_stats: true
  visualize_pocket_selection: false

# Smart Pocket Selection Configuration
pocket_selection:
  default_strategy: "adaptive"
  
  distance_based:
    primary_radius: 6.0
    secondary_radius: 12.0
    max_radius: 15.0
  
  surface_based:
    probe_radius: 1.4
    neighbor_radius: 5.0
    hydrophilic_bonus: 1.2
  
  residue_based:
    druggability_weights: true
    surface_accessibility_weight: 1.5
    distance_weight: 2.0
  
  binding_site:
    direct_contact_radius: 3.5
    extended_radius: 8.0
    chemical_property_bonus: true
  
  adaptive:
    prefer_binding_site: true
    fallback_to_distance: true
    hybrid_selection: true

# Model Architecture Details
architecture:
  joint2d3d:
    use_egnn: true  # Sử dụng EGNN backend
    egnn_edge_dim: 4
    egnn_fourier_features_2d: 0
    egnn_fourier_features_3d: 8
    egnn_num_neighbors: 32
    egnn_dropout: 0.1
    
  fusion:
    type: "enhanced"
    use_residual: true
    use_layer_norm: true
    
  conditioning:
    type: "add"
    pocket_dim_match_hidden: true

# Training Monitoring
monitoring:
  track_pocket_selection_efficiency: true
  log_atom_selection_statistics: true
  monitor_egnn_gradient_flow: false
  track_se3_equivariance: false
  
  selection_metrics:
    - "atoms_selected_per_pocket"
    - "selection_time_ms"
    - "strategy_usage_distribution"
    - "binding_site_coverage"

# Quick test mode (đặt test: true để test nhanh)
test_mode:
  enabled: false  # Đặt true để test với ít data
  max_train_samples: 100
  max_val_samples: 20
  num_epochs: 2
  batch_size: 4