# DDPM Training Configuration for Molecular Generation
# Optimized for CrossDock dataset with pocket conditioning

# Data configuration
data:
  train_path: "data/processed/train.pkl"
  val_path: "data/processed/test.pkl"  # Using test as val for now
  test_path: "data/processed/test.pkl"
  batch_size: 16  # Reduced for stability
  num_workers: 4
  pin_memory: true
  shuffle: true
  include_pocket: true
  augment: true
  max_atoms: 50

# Model architecture
model:
  # Basic molecular parameters
  atom_types: 11  # Based on CrossDock preprocessing
  bond_types: 4
  hidden_dim: 256
  pocket_dim: 256
  num_layers: 4
  max_radius: 10.0
  max_pocket_atoms: 1000
  
  # Conditioning strategy
  conditioning_type: "add"  # Options: "add", "concat", "gated"
  
  # Pocket selection strategy
  pocket_selection_strategy: "adaptive"  # "adaptive", "distance", "surface", "binding_site"
  interaction_radius: 8.0
  surface_probe_radius: 1.4

# DDPM diffusion parameters
ddpm:
  num_timesteps: 1000  # Standard DDPM
  beta_schedule: "cosine"  # "linear", "cosine", "sigmoid"
  beta_start: 0.0001
  beta_end: 0.02
  
  # Loss configuration
  loss_type: "mse"  # "mse", "l1", "huber"
  
  # Sampling parameters
  sampling_method: "ddpm"  # "ddpm", "ddim" (future)
  clip_denoised: true
  
# Training configuration
training:
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.0001
  grad_clip_norm: 1.0
  gradient_accumulation_steps: 1
  
  # Mixed precision training
  use_amp: true
  amp_dtype: "float16"
  
  # Learning rate scheduling
  scheduler:
    type: "cosine_annealing"
    T_max: 100
    eta_min: 0.00001
    warmup_epochs: 5
    warmup_lr: 0.00001

# Optimizer configuration
optimizer:
  type: "adamw"
  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001
  eps: 1e-8

# Loss weights
loss_weights:
  noise_loss: 1.0        # Main DDPM loss
  atom_type_loss: 0.1    # Auxiliary atom prediction
  bond_type_loss: 0.1    # Auxiliary bond prediction
  geometry_loss: 0.05    # Geometry consistency (optional)

# Logging configuration
logging:
  project_name: "crossdock-ddpm-molecular-generation"
  experiment_name: "ddpm-pocket-conditioning"
  log_every_n_steps: 50
  val_check_interval: 1000
  save_top_k: 3
  save_path: "models/ddpm/"
  
  # Wandb settings
  use_wandb: true
  wandb_tags: ["ddpm", "molecular-generation", "crossdock", "pocket-conditioning"]
  
  # Visualization
  visualize_molecules: true
  viz_frequency: 10  # Every 10 epochs
  num_viz_samples: 8

# Early stopping
early_stopping:
  monitor: "val_total_loss"
  patience: 15
  min_delta: 0.001
  mode: "min"

# Model checkpointing
checkpointing:
  monitor: "val_total_loss"
  save_best_only: true
  save_last: true
  mode: "min"
  filename: "ddpm-epoch-{epoch:02d}-loss-{val_total_loss:.4f}"

# Generation/Sampling configuration
generation:
  num_molecules: 100
  max_atoms: 50
  guidance_scale: 1.0
  
  # DDPM sampling parameters
  num_sampling_steps: 1000  # Can reduce for faster sampling
  eta: 0.0  # DDPM (1.0) vs DDIM (0.0)
  
  # Conditioning
  use_pocket_conditioning: true
  pocket_guidance_weight: 1.0

# Memory optimization
memory_optimization:
  gradient_checkpointing: false  # Enable if OOM
  max_batch_size_auto_tune: false
  empty_cache_every_n_steps: 100
  
  # Pocket size limits
  max_pocket_atoms_per_batch: 500
  smart_pocket_selection: true

# Hardware configuration
hardware:
  device: "auto"  # "auto", "cuda", "cpu"
  precision: "mixed"  # "full", "mixed"
  deterministic: false
  benchmark: true

# Reproducibility
seed: 42
deterministic: false

# Advanced DDPM options
advanced_ddpm:
  # Noise schedule improvements
  rescale_betas_zero_snr: false
  clip_sample: true
  clip_sample_range: 1.0
  
  # Training improvements
  prediction_type: "epsilon"  # "epsilon", "v_prediction", "sample"
  timestep_spacing: "leading"  # "leading", "linspace", "trailing"
  
  # Sampling improvements
  use_karras_sigmas: false
  sigma_min: 0.002
  sigma_max: 80.0

# Validation configuration
validation:
  val_frequency: 1  # Every epoch
  num_val_samples: 100
  compute_metrics: true
  
  # Molecular metrics to compute
  metrics:
    - "validity"
    - "uniqueness" 
    - "drug_likeness"
    - "tanimoto_similarity"
    - "scaffold_diversity"

# Dataset-specific settings
dataset_config:
  # CrossDock specific
  crossdock_version: "pocket10"
  use_split_by_name: true
  
  # Preprocessing
  center_molecules: true
  normalize_positions: false
  add_hydrogens: false
  
  # Augmentation
  rotation_augmentation: true
  noise_augmentation: true
  noise_scale: 0.1

# Debugging and development
debug:
  enable_debug_mode: false
  debug_batches: 10
  profile_training: false
  check_gradients: false
  
  # Data debugging
  visualize_first_batch: true
  print_model_summary: true
  log_memory_usage: false