# Minimal test config for debugging
data:
  train_path: "data/processed/train.pkl"
  val_path: "data/processed/test.pkl"  # Use test for val in minimal setup
  test_path: "data/processed/test.pkl"
  batch_size: 2  # Very small batch
  num_workers: 1
  pin_memory: false
  shuffle: true
  include_pocket: true
  augment: false
  max_atoms: 20  # Very small molecules

model:
  atom_types: 11
  bond_types: 4
  hidden_dim: 32  # Minimal hidden dim
  pocket_dim: 64  # Minimal pocket dim  
  num_layers: 1   # Just 1 layer for testing
  max_radius: 8.0
  max_pocket_atoms: 200  # Small pocket limit
  pocket_selection_strategy: "distance"  # Simplest strategy

sde:
  sigma_min: 0.01
  sigma_max: 10.0
  num_steps: 20  # Very few steps
  beta_schedule: "cosine"
  prediction_type: "score"

training:
  num_epochs: 1  # Just 1 epoch for testing
  lr: 0.01  # Higher LR for quick test
  weight_decay: 0.0001
  grad_clip_norm: 1.0
  
optimizer:
  type: "adamw"
  lr: 0.01
  betas: [0.9, 0.999]
  weight_decay: 0.0001
  
scheduler:
  type: "cosine_annealing"
  T_max: 1
  eta_min: 0.001
  
loss_weights:
  position_loss: 1.0
  atom_type_loss: 0.1
  bond_type_loss: 0.1
  
logging:
  project_name: "minimal-test"
  log_every_n_steps: 1
  val_check_interval: 10
  save_top_k: 1
  save_path: "models/"
  
early_stopping:
  monitor: "val_total_loss"
  patience: 3
  min_delta: 0.1
  
generation:
  num_molecules: 2
  max_atoms: 10
  guidance_scale: 1.0
  num_steps: 10
  sampling_method: "ddpm"