# Simple training config for quick start
data:
  train_path: "data/processed/train.pkl"
  val_path: "data/processed/val.pkl"
  test_path: "data/processed/test.pkl"
  batch_size: 8  # Small batch for testing
  num_workers: 2
  pin_memory: true
  shuffle: true
  include_pocket: true
  augment: true

model:
  atom_types: 11  # C, N, O, S, P, F, Cl, Br, I, H, Unknown
  bond_types: 4   # Single, Double, Triple, Aromatic
  hidden_dim: 64  # Smaller for quick training
  pocket_dim: 128
  num_layers: 3   # Fewer layers
  max_radius: 10.0

sde:
  sigma_min: 0.01
  sigma_max: 50.0
  num_steps: 200  # Fewer steps for faster training
  beta_schedule: "cosine"
  prediction_type: "score"

training:
  num_epochs: 5   # Few epochs for testing
  lr: 0.001
  weight_decay: 0.0001
  grad_clip_norm: 1.0
  accumulate_grad_batches: 1
  
optimizer:
  type: "adamw"
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.0001
  
scheduler:
  type: "cosine_annealing"
  T_max: 5
  eta_min: 0.00001
  
loss_weights:
  position_loss: 1.0
  atom_type_loss: 0.1
  bond_type_loss: 0.1
  
logging:
  project_name: "crossdock-molecular-sde-simple"
  log_every_n_steps: 20
  val_check_interval: 100
  save_top_k: 2
  save_path: "models/"
  
early_stopping:
  monitor: "val_total_loss"
  patience: 10
  min_delta: 0.001
  
generation:
  num_molecules: 10
  max_atoms: 30
  guidance_scale: 1.0
  num_steps: 100
  sampling_method: "ddpm"