data:
  train_path: "data/processed/train.pkl"
  val_path: "data/processed/val.pkl"
  test_path: "data/processed/test.pkl"
  batch_size: 16  # Reduced for memory efficiency
  num_workers: 4
  pin_memory: true
  shuffle: true
  include_pocket: true
  augment: true

model:
  atom_types: 11  # Updated for CrossDock atom types
  bond_types: 4   # Single, Double, Triple, Aromatic
  hidden_dim: 128
  pocket_dim: 256
  num_layers: 4
  max_radius: 10.0

sde:
  sigma_min: 0.01
  sigma_max: 50.0
  num_steps: 1000
  beta_schedule: "cosine"
  prediction_type: "score"

training:
  num_epochs: 200
  lr: 0.0005  # Slightly reduced
  weight_decay: 0.0001
  grad_clip_norm: 1.0
  accumulate_grad_batches: 1
  
optimizer:
  type: "adamw"
  lr: 0.0005
  betas: [0.9, 0.999]
  weight_decay: 0.0001
  
scheduler:
  type: "cosine_annealing"
  T_max: 200
  eta_min: 0.00001
  
loss_weights:
  position_loss: 1.0
  atom_type_loss: 0.1
  bond_type_loss: 0.1
  
logging:
  project_name: "crossdock-molecular-sde-generation"
  log_every_n_steps: 50
  val_check_interval: 500
  save_top_k: 3
  save_path: "models/"
  
early_stopping:
  monitor: "val_loss"
  patience: 30
  min_delta: 0.001
  
generation:
  num_molecules: 100
  max_atoms: 50
  guidance_scale: 1.5
  num_steps: 1000
  sampling_method: "ddpm"